### ISSUE TITLE
Add HTTPS support to current ESP32 firmware

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#12]
[repo](https://github.com/Liquid-Prep/LiquidPrep-Hardware/tree/platformio/Soil%20Moisture%20Sensor) using autoconnect library to join user wifi network.  For local development, this works fine, we will need to support HTTPS in production.

**Comment by IBMAngel** [comment]
in HTTPConnection.hpp had to change #include <hwcrypto/sha.h> to #include <esp32/sha.h>

**Comment by playground** [comment]
@IBMAngel FYI https://randomnerdtutorials.com/esp8266-nodemcu-https-requests/

**Comment by IBMAngel** [comment]
im having trouble working past this error, its a recent issue and haven't changed any lines of code.
![Screenshot 2023-02-03 at 3 05 42 PM](https://user-images.githubusercontent.com/109538235/216700921-0c685aaf-2cc5-4900-8e92-4faee60f53a7.png)

**Comment by playground** [comment]
Closing this as we are going to have SSL on express server.
