### ISSUE TITLE
Leverage ESP-NOW for two-way communications bridging between ESP32 

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#14]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_now.html

**Comment by Adamlip1334** [comment]
https://randomnerdtutorials.com/esp-now-esp32-arduino-ide/

**Comment by playground** [comment]
@Adamlip1334 https://www.hackster.io/CiferTech/iot-node-espnow-based-project-b1b0d7

**Comment by Adamlip1334** [comment]
finished 2 way esp communication here https://github.com/Adamlip1334/LiquidPrep-Hardware/tree/esp-now 
data is encapsulated in a vector, so still need to make a firmware that unpacks the vector and makes it readable for liquid-prep

**Comment by Adamlip1334** [comment]
https://github.com/Adamlip1334/LiquidPrep-Hardware/tree/websocket-unpack here is the last firmware that has websocket support for talking to liquid-prep
