### ISSUE TITLE
Create web tool UI to support different versions of firmware

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#17]
Currently, https://playground.github.io/liquid-prep-web-tools/ is hardcoded to only one version of the firmware to be flashed.  

Would like to introduce a UI to allow users to select a version they would like to flash.

**Comment by Adamlip1334** [comment]
Added support to add different firmware versions here. https://github.com/playground/liquid-prep-web-tools/pull/23

**Comment by playground** [comment]
Done.
