### ISSUE TITLE
Create a good README.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-liquid-prep#19]
This README needs better information:

1. Front matter
2. Shields - license should match LICENSE file
3. Description
4. Prerequisites
5. Installation
6. Usage
7. Advanced Details
8. Authors - should match MAINTAINERS.md

See examples of good README.md files:

* https://github.com/open-horizon-services/service-node-red-hello-world/blob/main/README.md
* https://github.com/open-horizon-services/service-fledge/blob/main/README.md
* https://github.com/open-horizon-services/service-homeassistant/blob/main/README.md

**Comment by harry251** [comment]
Could you assign me this issue? @joewxboy @playground

**Comment by joewxboy** [comment]
@harry251 You got it!  Let us know if you have any questions.

**Comment by harry251** [comment]
Of course. 

Do other sections look like okay with you? Also, I am a little lost how to write Installation

**Comment by playground** [comment]
I think we can add to them as we go.  Let me also add @Adamlip1334 and @IBMAngel, can you guys think of anything should be included in the [README](https://github.com/harry251/service-liquid-prep/tree/issue-19)?
