### ISSUE TITLE
Add ESP32 LoRa sensors support

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#2]

**Comment by playground** [comment]
@Adamlip1334 here is the [repo](https://github.com/Liquid-Prep/LiquidPrep-Hardware/tree/platformio/Soil%20Moisture%20Sensor) that you can use to flash the firmware onto your LoRa sensor.

**Comment by Adamlip1334** [comment]
I was able to flash the firmware of the esp32 w/ LoRa sensor and connect it with my network.

**Comment by Adamlip1334** [comment]
firmware with LoRa support - https://github.com/Adamlip1334/LiquidPrep-Hardware/tree/esp32-lora
