### ISSUE TITLE
Create Prompts and Completions for Edge Assistant

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#22]
We want to explore the options and capabilities of OpenAI with Prompt Engineering to provide Questions/Answers to all things about Edge Computing, more specifically for IEAM and Open Horizon.

There are two parts to this assignment, 
1) Train the model using Davinci as the base model
Here is the repo https://github.com/playground/openai-training to get started training the custom model with our custom dataset.

2) Integrate Code Engine backend with Slack
Here is the backend to be integrated with @Edge Assistant
https://github.com/playground/open-labs/tree/main/code-engine/edge-slack-bot

**Comment by joewxboy** [comment]
@playground Did we want to integrate this with the LFX Matrix chat server API, or with the LF Edge Slack API?  Since LF Edge is using a free Slack instance and Open Horizon is not currently using it, it might be better to use the Matrix server.  Let me know.

**Comment by playground** [comment]
Ok, I was aware that exists, thanks @joewxboy, I think LF Edge Slack would be great.

**Comment by IBMAngel** [comment]
I have an IBM tutorial that might be able to help with integrating the code engine. 
[Link](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-slack-chatbot-database-watson)
