### ISSUE TITLE
Add bluetooth logic for calibrating air and water values

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#34]
Branch off from https://github.com/Liquid-Prep/LiquidPrep-Hardware/tree/esp-now-wss

Add logic to support calibration similar to what was added [here](https://github.com/Liquid-Prep/LiquidPrep-Hardware/blob/4094247e398e8fdcc4d9820809e6ea4c334a44b5/esp-now/esp-mesh-bluetooth/src/main.cpp#L81)
in this [ticket](https://github.com/open-horizon-services/service-liquid-prep/issues/27)

**Comment by Adamlip1334** [comment]
Repo for Bluetooth logic for calibrating water values here [is in this repo.](https://github.com/open-horizon-services/service-liquid-prep/issues/url)
