### ISSUE TITLE
Add option to specify water value in percentage for calibration

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#35]
Depending on the type of soil, there may need a way to allow farmers to tweak the sensor measurement by specifying a value for calibrating water value.

Will need to update the UI and firmware logic.

**Comment by Adamlip1334** [comment]
Currently have the UI changed under [this branch ](https://github.com/open-horizon-services/service-liquid-prep/tree/calibration)

**Comment by Adamlip1334** [comment]
Firmware for communication from the UI [is in this repo.](url)
