### ISSUE TITLE
Explore time-series db's

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#4]

**Comment by Adamlip1334** [comment]
CouchBase and Redis -> Memory only options 
Allows a disk optional backed option
Probably best for data 10-20 mb max to avoid data failure
CouchBase seems to be easy to setup and run on a docker container

**Comment by playground** [comment]
@Adamlip1334 looks like Redis data could be stored in memory or persisted based on configuration  https://github.com/redis/node-redis, https://redis.io/docs/manual/cli/

**Comment by playground** [comment]
@Adamlip1334 https://en.wikipedia.org/wiki/Time_series_database looks like a good alternative to store our data
can you take a look to see if we can use this.  And here are docker images for it https://hub.docker.com/_/influxdb.

**Comment by playground** [comment]
Yet another alternative is https://github.com/edgexfoundry-holding/orra/tree/main/demos/OH-EXF-Kamakura
