### ISSUE TITLE
Add OTA via Bluetooth to esp-mesh-bluetooth firmware

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#42]
We want to provide the ability to update firmware via OTA with Bluetooth using [this branch](https://github.com/Liquid-Prep/LiquidPrep-Hardware/tree/bluetooth-ota-no-sleep/esp-now).  Use this as a reference https://michaelangerer.dev/esp32/ble/ota/2021/06/01/esp32-ota-part-1.html

**Comment by playground** [comment]
@Adamlip1334, just had a chance to test sleep mode branch, when it goes into light or deep sleep mode, it disables both bluetooth and wifi.  For esp-mesh-bluetooth firmware we do need the Bluetooth to be re-enabled when it wakes up.  Currently, I'm not sure if there is a way to do that.  We will need to do some investigation, check this out https://esp32.com/viewtopic.php?t=16286

So for now use this branch https://github.com/Liquid-Prep/LiquidPrep-Hardware/tree/bluetooth-ota-no-sleep/esp-now to implement Bluetooth OTA.

**Comment by Adamlip1334** [comment]
Firmware with OTA support here https://github.com/Adamlip1334/LiquidPrep-Hardware/tree/bluetooth-ota-no-sleep . I would still want to find a better way to select the firmware file.
