### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-liquid-prep#7]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by CKacper** [comment]
Hello assign me please :)

**Comment by harry251** [comment]
Could you assign me this issue? @joewxboy

**Comment by johnwalicki** [comment]
@harry251 I've assigned this issue to you.

**Comment by shvbsle** [comment]
@johnwalicki I think this issue can be closed since I already see a maintainers.md

**Comment by johnwalicki** [comment]
@shvbsle - agree. Yes. This commit added the MAINTAINERS.md file
https://github.com/open-horizon-services/service-liquid-prep/commit/3811fbc8e95d8ac4b34a1040823d3cd10259406a
