### ISSUE TITLE
Expose capacitance value to Liquid Prep App

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#71]
Currently esp-now mesh  are broadcasting the capitance value to the esp-now-gateway, we would like to send the values to the web server and be shown in the the Liquid Prep.

**Comment by Adamlip1334** [comment]
[Changes made in the Bluetooth-OTA-Nosleep](https://github.com/Adamlip1334/LiquidPrep-Hardware/tree/bluetooth-ota-no-sleep)
