### ISSUE TITLE
Incorporate PlantMate calibration and Moisture reading code into our firmware

### ISSUE THREAD

**Issue by playground** [open-horizon-services/service-liquid-prep#72]
@Adamlip1334 please create a version of the firmware to incorporate PlantMate code into both esp-now-gateway and esp-now-mesh.  create new folders such as esp-now-plantmate-gateway and esp-now-plantmate-mesh.   While you're in the code, also clean up the code as much as you can. Thanks.

**Comment by Adamlip1334** [comment]
Added plantmate logic [in branch here.](https://github.com/Adamlip1334/LiquidPrep-Hardware/tree/plantmate) Plantmate logic is in the firmware in folders esp-now-plantmate-gateway and esp-now-plantmate-mesh.
